os: linux
env:
  - CODACY_PROJECT_TOKEN=
dist: trusty
sudo: required
language: php
php:
  - '7.3'
before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.testing .env
script:
  - phpdbg -qrr vendor/bin/phpunit
services:
  - rabbitmq
cache:
  directories:
    - vendor
before_install:
  - sudo apt-get -qq update
  - composer self-update
  - composer install --no-interaction
after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml