<?php

namespace DataNoodle\Tests\integration;

use DataNoodle\Service;

class IntegrationService extends Service
{
    public function processSuccess()
    {
        // TODO: Implement processSuccess() method.
    }

    public function setHost()
    {
        $this->host = 'localhost';
    }

    public function setPort()
    {
        $this->port = 5672;
    }

    public function getHost()
    {
        return $this->host;
    }

    public function setVHost()
    {
        $this->vhost = '/';
    }

    public function getPort()
    {
        return $this->port;
    }

    public function getEnvVariables()
    {
        $this->setHost();
        $this->setPort();
        $this->setUser();
        $this->setPass();
        $this->setVHost();
    }

    public function setBadEnvVariables()
    {
        $this->setPort();
        $this->setUser();
        $this->setPass();
    }

    public function setUser()
    {
        $this->user = 'guest';
    }

    public function setPass()
    {
        $this->pass = 'guest';
    }

    public function getExchange()
    {
        return $this->exchange;
    }

    public function setQueue(
        $queue,
        $passive = false,
        $durable = true,
        $exclusive = false,
        $auto_delete = false,
        $nowait = false
    ) {
        parent::setQueue(
            $queue,
            $passive,
            $durable,
            $exclusive,
            $auto_delete,
            $nowait
        ); // TODO: Change the autogenerated stub
    }

    public function getQueue()
    {
        return $this->queue;
    }
}
